import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const guiderStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF6F0',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 10,
  },
  header: {
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 10,
  },
  exerciseTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2D2D2D',
    textAlign: 'center',
    marginBottom: 2,
  },
  exerciseCategory: {
    fontSize: 14,
    color: '#E7B58F',
    fontWeight: 'bold',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  carouselBox: {
    height: 440, // más alto para imagen grande
    width: width * 0.92,
    backgroundColor: '#FFF',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#E7B58F',
    marginBottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#E7B58F',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    overflow: 'hidden',
  },
  stepCard: {
    width: width * 0.92,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  imageWrapper: {
    backgroundColor: '#FFF6F0',
    borderRadius: 20,
    marginBottom: 18,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
  },
  stepImage: {
    width: 180, // más grande
    height: 180,
    borderRadius: 20,
  },
  stepTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E7B58F',
    marginBottom: 8,
    marginTop: 2,
    textAlign: 'center',
  },
  stepText: {
    fontSize: 16,
    color: '#4B4B4B',
    textAlign: 'center',
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  paginatorWrapper: {
    marginTop: 30,
    marginBottom: 10,
    alignItems: 'center',
    width: '100%',
  },
  nextButtonWrapper: {
    marginTop: 18,
    marginBottom: 18,
    alignItems: 'center',
    width: '100%',
  },
  footer: {
    marginTop: 18,
    marginBottom: 18,
    alignItems: 'center',
    width: '100%',
  },
  exitButton: {
    backgroundColor: '#FFEBEB',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 32,
    alignItems: 'center',
    marginTop: 6,
    elevation: 2,
  },
  exitButtonText: {
    color: '#FF5252',
    fontWeight: 'bold',
    fontSize: 16,
  },
  progressBarBackground: {
  width: 120,
  height: 8,
  backgroundColor: '#F3E3D3',
  borderRadius: 6,
  overflow: 'hidden',
  marginBottom: 6,
},
progressBarFill: {
  height: 8,
  backgroundColor: '#E7B58F',
  borderRadius: 6,
},
timerBox: {
  marginTop: 10,
  backgroundColor: '#FFF6E0',
  borderRadius: 12,
  paddingVertical: 6,
  paddingHorizontal: 18,
  borderLeftWidth: 4,
  borderLeftColor: '#E7B58F',
  overflow: 'hidden',
  position: 'relative',
  justifyContent: 'center',
  alignItems: 'center',
},
timerFill: {
  position: 'absolute',
  left: 0,
  top: 0,
  bottom: 0,
  backgroundColor: '#E7B58F',
  opacity: 0.25,
  borderRadius: 12,
  zIndex: 0,
},
timerText: {
  color: '#A07B50',
  fontSize: 15,
  fontWeight: 'bold',
  textAlign: 'center',
  zIndex: 1,
},
});

export default guiderStyles;