import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF6F0',
    paddingHorizontal: 16,
    paddingTop: 40,
  },
  backIcon: {
    position: 'absolute',
    top: 36,
    left: 16,
    zIndex: 10,
    borderRadius: 20,
    padding: 2,
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4B4B4B',
    marginTop: 16,
    marginBottom: 24,
    textAlign: 'center',
  },
  list: {
    paddingTop: 60,
    paddingBottom: 24,
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#E7B58F',
    padding: 18,
    marginBottom: 16,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D2D2D',
    marginBottom: 4,
  },
  cardDate: {
    fontSize: 13,
    color: '#A07B50',
    marginBottom: 6,
  },
  cardPreview: {
    fontSize: 14,
    color: '#4B4B4B',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBox: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E7B58F',
    width: '90%',
    maxHeight: '80%',
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 18,
    elevation: 8,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D2D2D',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalContent: {
    fontSize: 15,
    color: '#4B4B4B',
    textAlign: 'center',
    marginBottom: 18,
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 10,
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#E7B58F',
    alignItems: 'center',
    marginHorizontal: 4,
    backgroundColor: '#FFF6F0',
  },
  modalButtonText: {
    color: '#E7B58F',
    fontWeight: 'bold',
    fontSize: 16,
  },
});